-- ===================================================
-- ALTERAÇÃO DE SCHEMA: adiciona marca e quantidade_referencia
-- Execute isso ANTES do INSERT abaixo
-- ===================================================
ALTER TABLE public.materiais ADD COLUMN IF NOT EXISTS marca TEXT;
ALTER TABLE public.materiais ADD COLUMN IF NOT EXISTS quantidade_referencia NUMERIC;

-- Popula tabela materiais a partir da Lista de Referencia (201 itens)
INSERT INTO public.materiais (descricao_completa, unidade, categoria, marca, quantidade_referencia) VALUES
  ('Escova de Robinson reta', 'und', 'BROCAS (consumíveis/duráveis)', 'Preven', 18),
  ('Broca shofu ponta de chama', 'und', 'BROCAS (consumíveis/duráveis)', 'Dedeco', 12),
  ('Broca de tungstênio MAXICUT formato pera', 'und', 'BROCAS (consumíveis/duráveis)', NULL, 4),
  ('Broca de tungstênio MAXICUT formato agulha', 'und', 'BROCAS (consumíveis/duráveis)', NULL, 2),
  ('Discos de carborundum 22x0,6mm', 'und', 'BROCAS (consumíveis/duráveis)', NULL, 8),
  ('Polidor de Acrílico Exa-Technique PM (cinza, verde e amarela)', 'kit', 'BROCAS (consumíveis/duráveis)', 'Edenta', 2),
  ('Broca diamantada esférica 1017', 'und', 'BROCAS (consumíveis/duráveis)', 'Allprime', 12),
  ('Broca diamantada cilídrica 3122', 'und', 'BROCAS (consumíveis/duráveis)', 'Microdont', 12),
  ('Broca diamantada oval 3168', 'und', 'BROCAS (consumíveis/duráveis)', NULL, 12),
  ('Broca diamantada 2200 cônica', 'und', 'BROCAS (consumíveis/duráveis)', 'Angelus', 12),
  ('Mandril para roda (para adaptação em peça de mão)', 'und', 'BROCAS (consumíveis/duráveis)', 'Microdont', 6),
  ('Pedra montada branca tronco cônica para acabamento metais', 'und', 'BROCAS (consumíveis/duráveis)', 'Dedeco', 2),
  ('Feltro para metal 8mm', 'und', 'BROCAS (consumíveis/duráveis)', 'Tdv', 2),
  ('Ponta pedra Mizzi 22,0 x 3,1mm', 'und', 'BROCAS (consumíveis/duráveis)', 'DHPro', 2),
  ('Polidor metal lentilha rosa ou cinza', 'und', 'BROCAS (consumíveis/duráveis)', 'American Burrs', 2),
  ('Gancho ponta bola longo reto', 'pct 10und', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Tubo lingual p/ barra transpalatina para soldagem', 'pct 10und', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Botão lingual para colagem (reto)', 'pct 10und', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Botão lingual para soldagem (reto)', 'pct 10und', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Kit de Bandas para molares superiores universal', 'kit', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Kit de Bandas para molares inferiores universal', 'kit', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Kit de Bandas para pré-molares superiores universal', 'kit', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Mola aberta aço', 'rolo', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Tubo de Proteção Plástico cinza 022', 'rolo', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Mola Fechada NiTi Para Tração 7mm', 'pct 4un', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Mola Fechada NiTi Para Tração 9mm', 'pct 4un', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Mola Fechada NiTi Para Tração 12mm', 'pct 4un', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Mola Fechada NiTi Para Tração 15mm', 'pct 4un', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Mola NiTi Aberta 0,76mm', 'pct 3und', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Stop Ortodôntico Fechado Para Arcos Redondos', 'pct 25und', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Cera Ortodôntica Branca - Maquira', 'pct 10un', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Maquira', 5),
  ('Solda de Prata 0,8mm em Vareta', 'pct 10un', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Pasta Para Solda de Prata', 'vd', 'ACESSÓRIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Arco .012 termo ativado inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 4),
  ('Arco .012 termo ativado superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 4),
  ('Arco .014 termo ativado inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Arco .014 termo ativado superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Arco .016 termo ativado inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Arco .016 termo ativado superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Arco .018 termo ativado inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Arco .018 termo ativado superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Arco 16x16 termo ativado inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x16 termo ativado superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x22 termo ativado inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 6),
  ('Arco 16x22 termo ativado superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 6),
  ('Arco 19x25 termo ativado inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 6),
  ('Arco 19x25 termo ativado superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 6),
  ('Arco .012 niti inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .012 niti superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .014 niti inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .014 niti superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .016 niti inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .016 niti superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .018 niti inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .018 niti superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x16 niti inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x16 niti superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x22 niti inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x22 niti superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .012 aço inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .012 aço superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .014 aço inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .014 aço superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .016 aço inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .016 aço superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .018 aço inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco .018 aço superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco aço .020" inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco aço .020" superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x16 aço inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x16 aço superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x22 aço inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 16x22 aço superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco aço .019"x.025" inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 6),
  ('Arco aço .019"x.025" superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 6),
  ('Arco aço .021"x.025" inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco aço .021"x.025" superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 19x25 BRAIDED inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco 19x25 BRAIDED superior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Arco de curva reversa Niti .016 inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 1),
  ('Arco de curva reversa Niti .019x.025 inferior', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 1),
  ('Fio aço .016" – rolo', 'rolo', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Fio de aço 0,7mm – rolo', 'rolo', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Fio de aço 0,8mm – rolo', 'rolo', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Fio de aço 0,9mm – rolo', 'rolo', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Fio de amarrilho .008" rolo', 'rolo', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Fio de amarrilho .010" rolo', 'rolo', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Fio de amarrilho .012" rolo', 'rolo', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Fio TMA 19x25 vareta', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Fio Vareta TMA TiMo Redondo 0,36''''', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Fio Vareta Elgiloy 16x16', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Rocky Mountain Orthodontics', 2),
  ('Fio Vareta Elgiloy 16x22', 'pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Rocky Mountain Orthodontics', 2),
  ('Fio Vareta Morealloy 16x16 CoCr Ponta Azul', 'vareta pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Fio Twist Flex 3 Fios CrNi Redondo 0,015" (0,38mm)', 'vareta pct 10und', 'FIOS ORTODÔNTICOS (consumíveis)', 'Morelli', 3),
  ('Conjunto de braquetes convencional .022 Prescrição Capelozza I kit com 1 caso 5x5', 'kit', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Conjunto de braquetes convencional .022 Prescrição Capelozza II kit com 1 caso 5x5', 'kit', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Conjunto de braquetes convencional .022 Prescrição Capelozza III kit com 1 caso 5x5', 'kit', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 1),
  ('Conjunto de Braquetes Convencional .018 Prescrição Ricketts', '1 conj.', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 15),
  ('Tubo simples colagem Roth 16', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Tubo simples colagem Roth 26', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Tubo simples colagem Roth 36', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Tubo simples colagem Roth 46', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 7),
  ('Tubo duplo colagem Roth 16', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 2),
  ('Tubo duplo colagem Roth 26', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 2),
  ('Tubo duplo colagem Roth 36', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 2),
  ('Tubo duplo colagem Roth 46', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 2),
  ('Tubo simples soldagem Roth 16', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 4),
  ('Tubo simples soldagem Roth 26', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 4),
  ('Tubo simples soldagem Roth 36', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 4),
  ('Tubo simples soldagem Roth 46', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 4),
  ('Tubo duplo soldagem PLA Roth 36', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Tubo duplo soldagem PLA Roth 46', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Tubo duplo soldagem Roth 16', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Tubo duplo soldagem Roth 26', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Tubo duplo soldagem Roth 36', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Tubo duplo soldagem Roth 46', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 3),
  ('Tubo triplo soldagem Roth 16', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 2),
  ('Tubo triplo soldagem Roth 26', 'pct 10und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Orthometric', 2),
  ('Miniparafuso Ortodôntico Para Ancoragem Absoluta - 8mmx1mm', 'pct 2und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 8),
  ('Miniparafuso Ortodôntico Para Ancoragem Absoluta - 8mmx2mm', 'pct 2und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 8),
  ('Placa Lábio-Ativa Com Gancho .045 branca', 'und', 'APARELHOS ORTODÔNTICOS (consumíveis)', 'Morelli', 6),
  ('Elástico bengalinha cores variadas (multicores)', 'pct c/1000', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 10),
  ('Elástico bengalinha cinza', 'pct 10und', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 10),
  ('Elástico Ligadura Bengalinha Azul Bebê', 'pct 1000und', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Ligadura Bengalinha Rosa Bebê', 'pct 1000und', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Ligadura Bengalinha Azul', 'pct 1000und', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Ligadura Bengalinha Verde-mar', 'pct 1000und', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Ligadura Modular Sortido Cristal', 'pct 1000und', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 10),
  ('Elástico Intermaxilar 1/8" leve', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Elástico Intermaxilar 1/8" médio', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 1/8" pesado', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 3/16" leve', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Elástico Intermaxilar 3/16" médio', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 3/16" pesado', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico extraoral 1/2" médio', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico extraoral 1/2" pesado', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 1/2" Médio', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 1/2" Pesado', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 5/16" leve', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 5/16" médio', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 5/16" pesado', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 3/4" leve', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 3/4" médio', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Intermaxilar 3/4" pesado', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico Rotator cinza', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Elástico corrente cinza curto', 'rolo', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico corrente cinza médio', 'rolo', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico corrente cinza pesado', 'rolo', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 4),
  ('Elástico separador para dentes', 'pct', 'ELÁSTICOS ORTODÔNTICOS (consumíveis)', 'Morelli', 2),
  ('Cimento de ionômero de vidro para cimentação', 'vd.', 'RESINA/CIMENTO (consumíveis)', 'Meron', 3),
  ('Resina composta fotopolimerizável A2', 'und', 'RESINA/CIMENTO (consumíveis)', 'FiilMagic', 3),
  ('Resina composta Fluida A2', 'und', 'RESINA/CIMENTO (consumíveis)', 'Maquira', 3),
  ('Resina para colagem de braquetes', 'und', 'RESINA/CIMENTO (consumíveis)', 'Morelli', 6),
  ('Adesivo dentinário', 'und', 'RESINA/CIMENTO (consumíveis)', 'Dentsply', 4),
  ('Ácido fosfórico', 'und', 'RESINA/CIMENTO (consumíveis)', 'Angelus', 3),
  ('Ácido fluoridrico', 'und', 'RESINA/CIMENTO (consumíveis)', 'Angelus', 3),
  ('Aplicador Microbrush médio', 'pct', 'RESINA/CIMENTO (consumíveis)', 'Allprime', 4),
  ('Resina acrílica incolor (pó)', 'vd.', 'RESINA/CIMENTO (consumíveis)', 'JET', 2),
  ('Resina acrílica incolor (líquido)', 'vd.', 'RESINA/CIMENTO (consumíveis)', 'JET', 2),
  ('Resina Potenza Orthoblue', 'und', 'RESINA/CIMENTO (consumíveis)', 'Potenza', 3),
  ('Resina de Levante de Mordida Open Bite', 'seringa 4g', 'RESINA/CIMENTO (consumíveis)', 'Morelli', 4),
  ('Adesivo Ortodôntico Orthobond Plus', 'seringa 4g', 'RESINA/CIMENTO (consumíveis)', 'Morelli', 5),
  ('Adesivo Ortodôntico Orthoprimer', 'frasco 5g', 'RESINA/CIMENTO (consumíveis)', 'Morelli', 5),
  ('Papel Carbono para ajuste oclusal', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Bausch', 6),
  ('Tira lixa de aço 6mm', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Fava', 10),
  ('Agulha hipodérmica gengival curta', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Terumo', 1),
  ('Seringa com agulha 20 ml', 'und', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Injex', 6),
  ('Clorexidina gel c/ 2 unid. 3gr', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Biodinâmica', 1),
  ('Pedras pome', 'vd.', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Asfer', 2),
  ('Fio dental 200m', 'rolo', 'OUTROS MATERIAIS CONSUMO (consumíveis)', NULL, 2),
  ('Anestésico tópico 20% c/ 12 gr', 'vd.', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'DFL', 2),
  ('Anestésico injetável Lidocaína 100 1:2.500', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'SS White', 1),
  ('Roletes de algodão nº 1', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Cremer', 10),
  ('Roletes de algodão nº 2', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Cremer', 10),
  ('Gaze estéril 13 fios Estrela', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Cremer', 10),
  ('Cotonete c/ 150 unid.', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Melhormed', 5),
  ('Soro fisiológico 500ml', 'und', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Sorimax', 2),
  ('Vaselina sólida 30 gr', 'und', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Rioquímica', 2),
  ('Pasta profilática Herjos 90 gr', 'und', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Vigodent', 2),
  ('Gesso Tipo III', 'und', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Vigodent', 3),
  ('Cera 7 C/ 18 unidades', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Lysanda', 4),
  ('Cera utilidade', 'pct', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Lysanda', 3),
  ('Alginato Jeltrate', 'und', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Dentsply', 4),
  ('Álcool 92,8º', 'L', 'OUTROS MATERIAIS CONSUMO (consumíveis)', 'Prolink', 2),
  ('Máquina De Solda Kernit', 'und', 'EQUIPAMENTOS (duráveis)', 'Kernit', 1),
  ('Jato para Bráquete Jat Bracket', 'und', 'EQUIPAMENTOS (duráveis)', 'Essence Dental', 1),
  ('Resina Opallis Flow 2g', 'und', 'EQUIPAMENTOS (duráveis)', 'FGM', 4),
  ('Kit Adesivo Orthocem - Resina para Braquetes', 'kit', 'EQUIPAMENTOS (duráveis)', 'FGM', 6),
  ('Máscara Facial Petit Cor: Rosa', 'und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 3),
  ('Máscara Facial Petit Cor: Azul', 'und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 3),
  ('Banda Molar Universal Superior - Tamanho: 35', 'pct 10und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 2),
  ('Banda Molar Universal Superior - Tamanho: 38,5', 'pct 10und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 2),
  ('Banda Molar Universal Inferior - Tamanho: 34,5', 'pct 10und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 2),
  ('Banda Molar Universal Inferior - Tamanho: 35', 'pct 10und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 2),
  ('Banda Molar Universal Inferior - Tamanho: 38,5', 'pct 10und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 2),
  ('Espelho nº5 e cabo de espelho', 'und', 'EQUIPAMENTOS (duráveis)', 'Golgran', 32),
  ('Pinça de algodão', 'und', 'EQUIPAMENTOS (duráveis)', 'Golgran', 32),
  ('Porta-agulha MATHIEU 14 cm', 'und', 'EQUIPAMENTOS (duráveis)', 'Quinelato', 32),
  ('Dobrador de amarrilho', 'und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 32),
  ('Colocador e removedor de elastik de metal', 'und', 'EQUIPAMENTOS (duráveis)', 'Morelli', 32),
  ('Bandeja 22 x 9 x 1cm', 'und', 'EQUIPAMENTOS (duráveis)', 'SS White', 32);
